### PR TITLE
#270

### PR DESCRIPTION
**Pull request by pranotoism**
#270 molecule - Search

### CODE REVIEW

**Comment by ardiwine** [comment]
@pranotoism next time please use proper english word for each component even for ticket title/description >> molekul >>> molecule

**Comment by pranotoism** [comment]
> 
@ardiwine 

It was synchronized with the ticket which rika made via zenhub if I'm not mistaken. The title/description I addressed was only #270 and nothing more.

Nevertheless, good advice, Ko Edwin.

**Comment by gilangdarmawan** [comment]
Is this PR related to #8 @pranotoism ? Cause I have checked the other FMSearch component in #8

**Comment by pranotoism** [comment]
> Is this PR related to #8 @pranotoism ? Cause I have checked the other FMSearch component in #8

@gilangdarmawan 

oops my mistake

**Pull request closed without merging**
